# Generated by Django 5.2.4 on 2025-11-16 05:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Banner nomi')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner rasmi')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop/Notebook'), ('mobile', 'Mobile/Tablet')], max_length=10, verbose_name='Qurilma turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola (ixtiyoriy)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('elektronika', 'Elektronika'), ('uy_jihozlari', 'Uy jihozlari'), ('kiyim', 'Kiyim-kechak'), ('avto', 'Avto ehtiyot qismlar'), ('boshqa', 'Boshqa')], max_length=100, verbose_name='Kategoriya')),
                ('mahsulotturi', models.CharField(max_length=100, verbose_name='Mahsulot turi')),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('viloyat', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('fargona', 'Farg‘ona'), ('andijon', 'Andijon'), ('namangan', 'Namangan'), ('buxoro', 'Buxoro'), ('navoiy', 'Navoiy'), ('xorazm', 'Xorazm'), ('qashqadaryo', 'Qashqadaryo'), ('surxondaryo', 'Surxondaryo'), ('jizzax', 'Jizzax'), ('sirdaryo', 'Sirdaryo'), ('qoraqalpogiston', 'Qoraqalpog‘iston')], max_length=100, verbose_name='Viloyat')),
                ('tuman', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman/Shahar')),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Aniq manzil')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqam')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tavsif', models.TextField(blank=True, null=True, verbose_name='Batafsil tavsif')),
                ('sana', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('narx', models.CharField(default='0', max_length=20, verbose_name='Narx')),
                ('asosiyimg', models.ImageField(upload_to='asosiyimg/', verbose_name='Asosiy rasm')),
                ('birimg', models.ImageField(blank=True, null=True, upload_to='birimg/', verbose_name='1-rasm')),
                ('ikkiimg', models.ImageField(blank=True, null=True, upload_to='ikkiimg/', verbose_name='2-rasm')),
                ('uchuimg', models.ImageField(blank=True, null=True, upload_to='uchuimg/', verbose_name='3-rasm')),
                ('toltirish', models.FileField(blank=True, null=True, upload_to='toltirish/', verbose_name="Qo'shimcha fayl")),
                ('sotilgan', models.BooleanField(default=False, verbose_name='Sotildi')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('korishlar_soni', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Sevimli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Saqlangan sana')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fronend.mahsulot', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
                'unique_together': {('user', 'mahsulot')},
            },
        ),
    ]
