# Generated by Django 5.2.4 on 2025-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_profile_created_at_remove_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
